module.exports = {
  light: {
    description: 'Sensor de luz',
    units: 'lux',
    max: 65535,
    inverse: false,
    decimals: 0,
  },
  dht22_humidity: {
    description: 'Sensor de humedad',
    units: '%',
    max: 100,
    inverse: false,
    decimals: 2,
  },
  dht22_temperature: {
    description: 'Sensor de temperatura interior',
    units: 'ºC',
    inverse: false,
    decimals: 2,
  },
  temp1w: {
    description: 'Sensor de temperatura exterior',
    units: 'ºC',
    inverse: false,
    decimals: 2,
  },
  mcp_0: {
    description: 'Sensor de humedad en tierra 1',
    units: '%',
    max: 1024,
    inverse: true,
    decimals: 2,
  },
  mcp_1: {
    description: 'Sensor de humedad en tierra 2',
    units: '%',
    max: 1024,
    inverse: true,
    decimals: 2,
  },
  mcp_2: {
    description: 'Sensor de humedad en tierra 3',
    units: '%',
    max: 1024,
    inverse: true,
    decimals: 2,
  },
  mcp_3: {
    description: 'Sensor de humedad en tierra 4',
    units: '%',
    max: 1024,
    inverse: true,
    decimals: 2,
  },
  mcp_4: {
    description: 'Sensor de humedad en tierra 5',
    units: '%',
    max: 1024,
    inverse: true,
    decimals: 2,
  },
  mcp_5: {
    description: 'Sensor de humedad en tierra 6',
    units: '%',
    max: 1024,
    inverse: true,
    decimals: 2,
  },
  mcp_6: {
    description: 'Sensor de lluvia',
    units: '%',
    max: 1024,
    inverse: true,
    decimals: 2,
  },
  mcp_7: {
    description: 'Sensor de calidad del aire',
    units: 'ppm',
    max: 1024,
    inverse: false,
    decimals: 0,
  },
};